//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBackupper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList listboxItems1 {
            get {
                return ((global::System.Collections.ArrayList)(this["listboxItems1"]));
            }
            set {
                this["listboxItems1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList listboxItems2 {
            get {
                return ((global::System.Collections.ArrayList)(this["listboxItems2"]));
            }
            set {
                this["listboxItems2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList listboxItems3 {
            get {
                return ((global::System.Collections.ArrayList)(this["listboxItems3"]));
            }
            set {
                this["listboxItems3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList listboxItems4 {
            get {
                return ((global::System.Collections.ArrayList)(this["listboxItems4"]));
            }
            set {
                this["listboxItems4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList listboxItems5 {
            get {
                return ((global::System.Collections.ArrayList)(this["listboxItems5"]));
            }
            set {
                this["listboxItems5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList listboxItems6 {
            get {
                return ((global::System.Collections.ArrayList)(this["listboxItems6"]));
            }
            set {
                this["listboxItems6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList listboxItems7 {
            get {
                return ((global::System.Collections.ArrayList)(this["listboxItems7"]));
            }
            set {
                this["listboxItems7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList listboxItems8 {
            get {
                return ((global::System.Collections.ArrayList)(this["listboxItems8"]));
            }
            set {
                this["listboxItems8"] = value;
            }
        }
    }
}
